version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8089:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
            - php
            - mysqldb

    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
    mysqldb:
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_ROOT_HOST=192.168.0.48/255.255.255.248
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: 'always'
        expose:
            - '8989'
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
            network:
                ipv4_address: 172.20.0.2
networks:
    network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
    code-network:
        driver: bridge
